name = "statikapi-cf-demo"
main = "dist/worker.mjs"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "STATIK_PUBLIC_BUCKET"
bucket_name = "REPLACE_ME_PUBLIC_BUCKET"

[[r2_buckets]]
binding = "STATIK_PRIVATE_BUCKET"
bucket_name = "REPLACE_ME_PRIVATE_BUCKET"

[[kv_namespaces]]
binding = "STATIK_MANIFEST"
id = "REPLACE_ME_KV_NAMESPACE_ID"

[vars]
STATIK_BUILD_TOKEN = "REPLACE_ME_STATIK_BUILD_TOKEN"
STATIK_SRC = "src-api"   # optional: lets the CLI auto-detect
STATIK_USE_INDEX_JSON = "false"
STATIK_PUBLIC_BUCKET_BINDING = "STATIK_PUBLIC_BUCKET"
STATIK_PRIVATE_BUCKET_BINDING = "STATIK_PRIVATE_BUCKET"
STATIK_PRIVATE_AUTH_HEADER_NAME = "x-statik-private-auth"
STATIK_PRIVATE_AUTH_HEADER_VALUE = "REPLACE_ME_PRIVATE_AUTH_VALUE"
STATIK_WORKER_REQUEST_LIMIT = "0"
STATIK_R2_CLASS_A_LIMIT = "0"
STATIK_R2_CLASS_B_LIMIT = "0"
STATIK_MANIFEST_BINDING = "STATIK_MANIFEST"
