blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/statikapi/statikapi/security/policy
    about: Please report security issues privately following our security policy.
