#!/usr/bin/env node
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import url from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const cliRoot = path.resolve(__dirname, '..'); // packages/cli
const repoRoot = path.resolve(cliRoot, '../../');
const uiPkg = path.resolve(cliRoot, '../../packages/ui'); // packages/ui
const uiDist = path.join(uiPkg, 'dist');
const destinations = [
  {
    dir: path.join(cliRoot, 'ui'),
    note: `This folder is generated during publish by packages/cli/scripts/embed-ui.js
and contains the prebuilt StatikAPI UI that the CLI serves at /_ui.\n`,
  },
  {
    dir: path.join(repoRoot, 'packages/adapter-cloudflare/ui'),
    note: `This folder is generated by packages/cli/scripts/embed-ui.js
and contains the prebuilt StatikAPI UI that the Cloudflare preview serves at /_ui.\n`,
  },
];

function exists(p) {
  try {
    fs.accessSync(p);

    return true;
  } catch {
    return false;
  }
}

async function rimraf(p) {
  await fsp.rm(p, { recursive: true, force: true });
}

async function copyDir(src, dst) {
  await fsp.mkdir(dst, { recursive: true });

  const entries = await fsp.readdir(src, { withFileTypes: true });

  for (const e of entries) {
    const s = path.join(src, e.name);
    const d = path.join(dst, e.name);
    if (e.isDirectory()) await copyDir(s, d);
    else if (e.isFile()) await fsp.copyFile(s, d);
  }
}

(async () => {
  // 1) build UI if needed
  if (!exists(uiDist)) {
    try {
      // Build the UI package from the workspace root
      execSync('pnpm -w --filter @statikapi/ui build', {
        stdio: 'inherit',
        cwd: repoRoot,
      });
    } catch (e) {
      console.error('[statikapi] Failed to build @statikapi/ui:', e?.message || e);

      process.exit(1);
    }
  }
  if (!exists(uiDist)) {
    console.error('[statikapi] @statikapi/ui build did not produce "dist".');

    process.exit(1);
  }

  // 2) copy into every embedded UI target
  for (const target of destinations) {
    await rimraf(target.dir);
    await copyDir(uiDist, target.dir);
    await fsp.writeFile(path.join(target.dir, 'EMBEDDED_UI_README.txt'), target.note, 'utf8');
    console.log(`[statikapi] Embedded UI → ${path.relative(process.cwd(), target.dir)}`);
  }
})().catch((e) => {
  console.error(e);

  process.exit(1);
});
